import { Geist, Geist_Mono,Noto_Sans } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "../components/blocks/shadcnblocks-com-navbar1";

const geistSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Noto_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[#020001]  ${geistSans.variable} ${geistSans.className} ${geistMono.variable} antialiased`}
      >
     <Navbar1/>
        {children}
      </body>
    </html>
  );
}
